import Head from 'next/head'
import { Container } from '@showtime-org/ui/src/components/atoms/Container'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="flex items-center">
            Request existing admins for the admin role!
          </div>
        </Container>
      </main>
    </>
  )
}
