import Head from 'next/head'
import { Container } from '@showtime-org/ui/src/components/atoms/Container'
import { CreateShowtime } from '@showtime-org/ui/src/components/templates/CreateShowtime'
import { FormProviderCreateShowtime } from '@showtime-org/forms/src/createShowtime'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Showtime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <FormProviderCreateShowtime>
            <CreateShowtime />
          </FormProviderCreateShowtime>
        </Container>
      </main>
    </>
  )
}
