import { SearchCinemas } from '@showtime-org/ui/src/components/templates/SearchCinemas'
import Head from 'next/head'

export default function Login() {
  return (
    <>
      <Head>
        <title>Showtime - Search movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchCinemas />
      </main>
    </>
  )
}
