import Head from 'next/head'
import { Container } from '@showtime-org/ui/src/components/atoms/Container'

export default function Faq() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="mb-2 text-xl font-semibold">Contact</div>
          <div className="max-w-md space-y-4 text-lg">
            <p>
              Hey there! I&apos;m Karthick Ragavendran, the creator of this
              extraordinary demo application.
            </p>{' '}
            <p>
              When I&apos;m not busy crafting the most delightful and
              entertaining movie ticket booking experience, you can find me
              penning captivating stories, composing enchanting music, or
              basking in the beauty of rain and cloudy days. I&apos;m a man of
              many passions, and I love weaving them all into the tapestry of my
              life!
            </p>{' '}
            <p>
              Now, if you&apos;re curious to know more about my adventures or
              just want to say &quot;Hi,&quot; feel free to connect with me
              through the wondrous realms of LinkedIn, YouTube, Medium, and
              other magical platforms.
            </p>{' '}
            <p>
              Just click on the enchanted links, and you&apos;ll be transported
              to my world of creativity, inspiration, and endless cups of hot
              cocoa on a rainy day! Oh, and if you happen to be on the lookout
              for a full-time full-stack developer who&apos;s as passionate
              about coding as they are about rainy days, I might just be your
              guy! So, go ahead, and let&apos;s share our dreams and aspirations
              together.
            </p>
            <p>I can&apos;t wait to hear from you!</p>
          </div>
        </Container>
      </main>
    </>
  )
}
