import Head from 'next/head'
import { AuthLayout } from '@showtime-org/ui/src/components/molecules/AuthLayout'
import { LoginForm } from '@showtime-org/ui/src/components/templates/LoginForm'
import { Accordion } from '@showtime-org/ui/src/components/molecules/Accordion'
import { Container } from '@showtime-org/ui/src/components/atoms/Container'

type FAQFormat = { question: string; answer: string }
export const faqs: FAQFormat[] = [
  {
    question: 'If I buy a ticket, do I get a free popcorn tree?',
    answer:
      "While we'd love to offer you a lifetime supply of popcorn, a popcorn tree is not included with a ticket purchase. But hey, feel free to grab some popcorn at the concession stand!",
  },
  {
    question: 'Can I bring my pet llama to the movies with me?',
    answer:
      'As much as we adore fluffy llamas, our theaters are designed for human guests only. Your llama can enjoy a movie night at home instead!',
  },
  {
    question:
      "Is it true that if I wear 3D glasses throughout the entire movie, I'll gain superpowers?",
    answer:
      "Unfortunately, 3D glasses don't grant superpowers, but they do make 3D movies look extra cool! Just remember to take them off before you leave the theater, or you might see the world in a whole new dimension.",
  },
  {
    question: 'If I laugh too hard during the movie, will I be charged extra?',
    answer:
      "Absolutely not! We encourage all forms of laughter, giggles, and chuckles. The louder, the better - it's contagious!",
  },
  {
    question: "Can I bring my own director's chair and megaphone to the movie?",
    answer:
      "While we appreciate your enthusiasm, we kindly request that you leave your director's chair and megaphone at home. Our comfy seats and surround sound system have got you covered!",
  },
  {
    question:
      'What happens if I spill soda on my ticket? Will I turn into a superhero?',
    answer:
      'While spilling soda on your ticket may not result in superpowers, it could make your ticket a sticky mess! Make sure to keep your ticket safe and dry to avoid any unexpected mishaps.',
  },
  {
    question:
      'Is there a secret password to access a hidden theater with unlimited movies?',
    answer:
      "We love a good secret, but there's no hidden theater password. You'll have to rely on the old-fashioned way of buying a ticket for each movie you want to see!",
  },
  {
    question: 'Can I time travel if I watch a movie set in the past or future?',
    answer:
      "Sadly, watching a movie set in a different time period won't grant you time-traveling abilities, but it's a fun way to escape reality for a couple of hours!",
  },
  {
    question:
      'If I eat too much popcorn, will I start popping out popcorn kernels?',
    answer:
      "No need to worry! While popcorn is delicious, consuming it won't cause you to pop out kernels. Feel free to indulge without fear!",
  },
  {
    question:
      'Will wearing a cape to the theater make the movie experience more epic?',
    answer:
      "Capes are always a fun fashion statement, but they won't affect the movie-watching experience. Feel free to wear one, though, and show off your superhero style!",
  },
]

export default function Faq() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="mb-2 text-xl font-semibold">Faqs</div>
          {faqs.map((faq) => (
            <Accordion
              key={faq.question}
              title={<div className="max-w-md">{faq.question}</div>}
            >
              <div className="max-w-md">{faq.answer}</div>
            </Accordion>
          ))}
        </Container>
      </main>
    </>
  )
}
